name: bbm
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  # Core dependencies
  - python=3.8
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - ipython
  - ipywidgets
  - tqdm
  - pillow
  - zlib
  - xz
  - ncurses

  # PyTorch and related packages
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - pytorch-cuda=11.8

  # Additional pip dependencies
  - pip:
      - omegaconf==2.3.0
      - transformers==4.39.3
      - datasets==2.18.0
      - huggingface-hub==0.22.2
      - tiktoken==0.6.0
      - aiohttp==3.9.3
      - wandb==0.16.6
      - safetensors==0.4.2
      - regex==2023.12.25
      - tokenizers==0.15.2
      - jupyterlab==4.1.6
      - notebook==7.1.2
      - matplotlib-inline==0.1.6
      - pyarrow==15.0.2
